#!/bin/bash
#iverilog -o $EDA_env_dir/test $src_dir/*/*.v $src_dir/top/TbAll.sv && vvp -n $EDA_env_dir/test
#src_dir=../src
cd iverilog-project && iverilog -D DUMP_VCD -o test filelist.v  && vvp -n test && cd -
