`define ALU_OP_WIDTH	5
`define ALU_ADD    		`ALU_OP_WIDTH'd0
`define ALU_SUB    		`ALU_OP_WIDTH'd1
`define ALU_AND    		`ALU_OP_WIDTH'd2
`define ALU_OR     		`ALU_OP_WIDTH'd3
`define ALU_XOR    		`ALU_OP_WIDTH'd4
`define ALU_SLT    		`ALU_OP_WIDTH'd5
`define ALU_SLL    		`ALU_OP_WIDTH'd6
`define ALU_SLTU   		`ALU_OP_WIDTH'd7
`define ALU_SRL    		`ALU_OP_WIDTH'd8
`define ALU_SRA    		`ALU_OP_WIDTH'd9
`define ALU_COPY_A 		`ALU_OP_WIDTH'd10
`define ALU_COPY_B 		`ALU_OP_WIDTH'd11
`define ALU_BEQ         `ALU_OP_WIDTH'd12
`define ALU_BNE         `ALU_OP_WIDTH'd13
`define ALU_BLT         `ALU_OP_WIDTH'd14
`define ALU_BLTU        `ALU_OP_WIDTH'd15
`define ALU_BGE         `ALU_OP_WIDTH'd16
`define ALU_BGEU        `ALU_OP_WIDTH'd17
`define ALU_JAL         `ALU_OP_WIDTH'd18
`define ALU_JALR        `ALU_OP_WIDTH'd19
`define ALU_CSR         `ALU_OP_WIDTH'd20
