webtalk_init -webtalk_dir /home/ubuntu/Music/NF5_Cache_jzk_ex/vivado-project/NF5_System/NF5_System.sim/sim_1/behav/xsim/xsim.dir/Core_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Jan 27 10:57:08 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d9cb3d50c59c5fd5aec1cd7e3d31a8fb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a60e9bbc7f7d4e2abf1bae28d2a3a211" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "8" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.4 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808.002 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.02_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "130160_KB" -context "xsim\\usage"
webtalk_transmit -clientid 530954784 -regid "" -xml /home/ubuntu/Music/NF5_Cache_jzk_ex/vivado-project/NF5_System/NF5_System.sim/sim_1/behav/xsim/xsim.dir/Core_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/ubuntu/Music/NF5_Cache_jzk_ex/vivado-project/NF5_System/NF5_System.sim/sim_1/behav/xsim/xsim.dir/Core_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/ubuntu/Music/NF5_Cache_jzk_ex/vivado-project/NF5_System/NF5_System.sim/sim_1/behav/xsim/xsim.dir/Core_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
