#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2018.2 (64-bit)
#
# Filename    : NF5_System.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sat Jan 30 22:23:52 CST 2021
# SW Build 2258646 on Thu Jun 14 20:02:38 MDT 2018
#
# Copyright 1986-2018 Xilinx, Inc. All Rights Reserved. 
#
# usage: NF5_System.sh [-help]
# usage: NF5_System.sh [-lib_map_path]
# usage: NF5_System.sh [-noclean_files]
# usage: NF5_System.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'NF5_System.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib blk_mem_gen_v8_3_6 axi_bram_ctrl_v4_0_14 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_17 fifo_generator_v13_2_2 axi_data_fifo_v2_1_16 axi_crossbar_v2_1_18 util_vector_logic_v2_0_1)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "NF5_System.sh - Script generated by export_simulation (Vivado v2018.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/ec67/hdl" \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ip/NF5_System_SRAM_0_0/sim/NF5_System_SRAM_0_0.v" \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ip/NF5_System_SRAM_1_0/sim/NF5_System_SRAM_1_0.v" \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/sim/NF5_System.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work blk_mem_gen_v8_3_6 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/ec67/hdl" \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/2751/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_bram_ctrl_v4_0_14 $vhdlan_opts \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/6db1/hdl/axi_bram_ctrl_v4_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ip/NF5_System_axi_bram_ctrl_0_4/sim/NF5_System_axi_bram_ctrl_0_4.vhd" \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ip/NF5_System_axi_bram_ctrl_0_5/sim/NF5_System_axi_bram_ctrl_0_5.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/ec67/hdl" \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ip/NF5_System_Core_0_2/sim/NF5_System_Core_0_2.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/ec67/hdl" \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/ec67/hdl" \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_17 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/ec67/hdl" \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/6020/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/ec67/hdl" \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/7aff/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_2 $vhdlan_opts \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/ec67/hdl" \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/7aff/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_16 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/ec67/hdl" \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/247d/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_18 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/ec67/hdl" \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/15a3/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/ec67/hdl" \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ip/NF5_System_xbar_0/sim/NF5_System_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work util_vector_logic_v2_0_1 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/ec67/hdl" \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/2137/hdl/util_vector_logic_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ipshared/ec67/hdl" \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ip/NF5_System_util_vector_logic_0_0/sim/NF5_System_util_vector_logic_0_0.v" \
    "$ref_dir/../../../../NF5_System.srcs/sources_1/bd/NF5_System/ip/NF5_System_util_vector_logic_0_1/sim/NF5_System_util_vector_logic_0_1.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.NF5_System xil_defaultlib.glbl -o NF5_System_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./NF5_System_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./NF5_System.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/ubuntu/vivado/NF5_Cache_jzk_ex/vivado-project/NF5_System/NF5_System.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key NF5_System_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc NF5_System_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./NF5_System.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: NF5_System.sh [-help]\n\
Usage: NF5_System.sh [-lib_map_path]\n\
Usage: NF5_System.sh [-reset_run]\n\
Usage: NF5_System.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
