webtalk_init -webtalk_dir /home/ubuntu/vivado/NF5_Cache_jzk_ex/vivado-project/NF5_System/NF5_System.sim/sim_1/behav/xsim/xsim.dir/system_test_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jan 31 10:10:07 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4f11bc1a-84c1-4578-abaf-f47fd3104f95" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "a60e9bbc7f7d4e2abf1bae28d2a3a211" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3042" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.7 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2207.991 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "6.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1009300 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "67.88_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "203724_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3490530191 -regid "" -xml /home/ubuntu/vivado/NF5_Cache_jzk_ex/vivado-project/NF5_System/NF5_System.sim/sim_1/behav/xsim/xsim.dir/system_test_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/ubuntu/vivado/NF5_Cache_jzk_ex/vivado-project/NF5_System/NF5_System.sim/sim_1/behav/xsim/xsim.dir/system_test_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/ubuntu/vivado/NF5_Cache_jzk_ex/vivado-project/NF5_System/NF5_System.sim/sim_1/behav/xsim/xsim.dir/system_test_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
